# Generated by Django 4.1.2 on 2022-11-06 10:17

import clickhouse_backend.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', clickhouse_backend.models.GenericIPAddressField(default='::')),
                ('sport', clickhouse_backend.models.PositiveSmallIntegerField(default=0)),
                ('dst_ip', clickhouse_backend.models.GenericIPAddressField(default='::')),
                ('dport', clickhouse_backend.models.PositiveSmallIntegerField(default=0)),
                ('transport', models.CharField(default='', max_length=3)),
                ('protocol', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('length', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Network event',
                'db_table': 'event',
                'ordering': ['-id'],
                'engine': clickhouse_backend.models.ReplacingMergeTree(order_by=('dst_ip', 'timestamp'), partition_by=models.Func('timestamp', function='toYYYYMMDD')),
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=clickhouse_backend.models.Index(fields=['src_ip', 'dst_ip'], granularity=4, name='src_ip_dst_ip_idx', type=clickhouse_backend.models.Set(1000)),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('dport__lte', 65535), ('sport__gte', 0)), name='sport_range'),
        ),
    ]
