[tox]
requires =
    tox>=4
env_list =
    py{3.10,3.11}-django{5.0,5.1,5.2}
    py{3.12,3.13,3.14}-django{5.0,5.1,5.2,6.0}

[variables]
code = clickhouse_backend example tests

[testenv]
setenv =
    PYTHONUNBUFFERED = 1
deps =
    django5.0: Django>=5.0,<5.1
    django5.1: Django>=5.1,<5.2
    django5.2: Django>=5.2,<6.0
    django6.0: Django>=6.0,<6.1
    coverage
commands =
    pip install pandas
    # Use local clickhouse_backend package so that coverage works properly.
    pip install -e .
    coverage run tests/runtests.py --debug-sql {posargs}
