name: Test main

on:
  push:
    branches: ["main"]

jobs:
  test:
    uses: ./.github/workflows/base-test.yml
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
    secrets: inherit
